version: "3.3"

services:
    app_frontend:
      build:
        context: ./card-transfer
        dockerfile: Dockerfile
      ports:
        - 3000:3000
    app_backend:
      build:
        context: ./TransferMoneyApp
        dockerfile: Dockerfile
      ports:
        - 5500:5500